# Site settings
title: "Edison Orellana"
email: me@edisonorellana.com 
description: "Personal website for Edison Orellana"
baseurl: ""
url: "edison.me"
title_description: "Geographic Information Science graduate from the University of Illinois at Urbana Champaign"
title_image: "https://gravatar.com/avatar/56b00aca58d5c1b7ddcca365ab0f7df4?s=512"
google_analytics: ""
disqus_account: edisondotme
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: edisondotme
github_username:  edisondotme
facebook_url: facebook.com/edisondotme

# Footer
footer_left: ""
footer_right: ""

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
