permalink: /:categories/:title.html
url: "http://www.edisonorellana.com/"
full_name: "Edison Orellana"
first_name: "Edison"
last_name: "Orellana"
blog_title: "Edison Orellana"
author_img_name_path: "/images/users/me.jpg"
disqus_shortname: "annuit02"
copyright_year: "2015"
google_analytics_code: ""
aboutme: "Follow my directions."
twitter: "annuit02"
github: "annuit02"
facebook: "edisonorellana"
linkined_url: ""
base_url: "/testsite"