# Site settings
title: "Edison Orellana"
email: "me@edison.com" 
description: "Personal website for Edison Orellana"
baseurl: ""
url: "https://edison.me"
enforce_ssl: "edison.me"
author_name: "Edison Orellana"
title_description: "Geographic Information Science graduate from the University of Illinois at Urbana-Champaign
        [View my Resume](https://edison.me/resources/Edison-Orellana-resume.pdf)"
title_image: "https://gravatar.com/avatar/56b00aca58d5c1b7ddcca365ab0f7df4?s=512"
google_analytics: "UA-82428263-1"
disqus_account: "edisondotme"
# addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: edisondotme
github_username:  edisondotme
facebook_url: facebook.com/edisondotme

# Footer
footer_left: ""
footer_right: ""

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: ["CNAME",
          "README.md"]
